project:
  type: website
  output-dir: docs

website:
  title: "fusionACS"
  image: fusionACS_badge.jpg
  navbar:
    left:
      - text: "About"
        href: about.qmd    # Links to your About page
      - text: "Details"
        href: details.qmd    # Links to your About page
      - text: "Results"
        href: results.qmd    # Links to your About page
      - text: "Team"
        href: team.qmd    # Links to your Team page
      - text: "FAQ"
        href: faq.qmd  # Links to your Contact page
   author:
    - name: "Kevin Ummel"
      affiliation: "Greenspace Analytics"
      email: "kevin.ummel@yale.edu"
      github: "https://github.com/ummel"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

