project:
  type: website
  output-dir: docs

website:
  title: "fusionACS"
  navbar:
    logo: fusionACS_badge.jpg
    left:
      - text: "About"
        href: about.qmd
      - text: "Details"
        href: details.qmd
      - text: "Results"
        href: results.qmd
      - text: "Team"
        href: team.qmd
      - text: "FAQ"
        href: faq.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

