---
title: "Publications"
---

### Citing fusionACS

Any use of fusionACS outputs should cite Ummel et al. (2024):

* Ummel, Kevin, Miguel Poblete-Cazenave, Karthik Akkiraju, Nick Graetz, Hero Ashman, Cora Kingdon, Steven Herrera Tenorio, Aaryaman Sunny Singhal, Daniel Aldana Cohen, and Narasimha D. Rao. 2024. “Multidimensional Well-Being of US Households at a Fine Spatial Scale Using Fused Household Surveys.” Scientific Data 11 (142). [https://doi.org/10.1038/s41597-023-02788-7](https://doi.org/10.1038/s41597-023-02788-7).

Any use of fusionACS estimates for locales smaller than Public Use Microdata Areas (PUMA's) should also cite Tuccillo et al. (2023):

* Tuccillo, Joseph V., Robert Stewart, Amy Rose, Nathan Trombley, Jessica Moehl, Nicholas Nagle, and Budhendra Bhaduri. 2023. “UrbanPop: A Spatial Microsimulation Framework for Exploring Demographic Influences on Human Dynamics.” Applied Geography 151: 102844. [https://doi.org/10.1016/j.apgeog.2022.102844](https://doi.org/10.1016/j.apgeog.2022.102844). 

### Publications using fusionACS

* Brown, M., Becker, J. M., Carbone, J. C., Goforth, T., McFarland, J., Nock, D., Pitman, K., & Steinberg, D. 2024. Tax credits for clean electricity: The distributional impacts of supply-push policies in the power sector. Journal of the Association of Environmental and Resource Economists, 11(S1), S199–S229. [https://doi.org/10.1086/730923](https://doi.org/10.1086/730923)

